### ISSUE TITLE
Genel

### ISSUE THREAD

**Issue by VB10** [hakandl/taby#1]
Eline emeğine sağlık bir kaç nokta ilerisi için önemli
- alt methodlarında misal provider dan data okurken doğrudan contexten okuma misal o metroda git param al ve onu ver bu sayede methodun gelişmeye ve context den uzak olur
bu genel tüm viewmodel uygulanmalı 
- json modellerini immutable yapmak önemli equtable etc
- widget parçalamaların güzel onun dışında height değerlerini bir yerde toplarsan oda ilerisi için iui olabilir 
- vm katmanında çok fazla ui Logic bulundurma misal araya bir katman daha ekle o ui haberleştisin sen ana Logic'ini yap

**Comment by hakandl** [comment]
Tesekkur ederim, bunlari not aldim ve kontrol edecegim
